### PR TITLE
SLING-9464 - Use a ManagedServiceFactory to avoid polling

### PR DESCRIPTION
**Pull request by cschneider**

### CODE REVIEW

**Comment by tmaret** [comment]
That's an interesting approach if there is a guarantee that the `ManagedServiceFactory` is called for configurations created _before_ the `ManagedServiceFactory` was activated.

**Comment by cziegeler** [comment]
Yes, a ManagedServiceFactory is called with every configuration matching - regardless whether the configuration was created before or after the MSF is registered

**Comment by tmaret** [comment]
Thanks @cziegeler ! So @cschneider I think this is an improvement over #32. Could you polish the PR ? It seems the tests got removed and dead code has emerged ;-)

**Comment by tmaret** [comment]
Minor fix, the configAdmin is no longer required.
Other than that, LGTM, thanks @cschneider!

**Pull request merged**
