### PR TITLE
SLING-9537 - Emit metric for error accessing queues

### PR DESCRIPTION
**Pull request by amit-jain**
- Emit metric (counter)
- Tests

### CODE REVIEW

**Comment by amit-jain** [comment]
@tmaret Please review. A point in particular I am not very sure is whether a wrong queue name should also be covered by this metric (In the PR it is)?

**Comment by tmaret** [comment]
Thanks @amit-jain ! The implementation returns a queue for any name. We should not cover this in the error budget.

**Comment by tmaret** [comment]
Scratch, we actually check for wrong queue names since SLING-9049.

**Comment by tmaret** [comment]
LGTM, thanks @amit-jain !

**Pull request merged**
