### PR TITLE
SLING-12024 - Import package if status message for later package alre…

### PR DESCRIPTION
**Pull request by cschneider**
…ady arrived

### CODE REVIEW

**Comment by joerghoh** [comment]
Can you create an OSGI property to enable this feature?

**Review by tmaret — CHANGES_REQUESTED** [review]
I think one changes is required.

Higher status must be managed by sub agent name. Indeed, package offsets are guaranteed to be semantically increasing per agent, but agents interleave message on the same topic. 

Could we consider restarting the pod instead of considering the offset to be imported ? In rare cases, the package will be imported when it should not and that will cause inconsistencies.

**Comment by cschneider** [comment]
Managing status by sub agent makes sense. I will take care of it.
Restarting the pod is an interesting idea. We could do it like for the blocked queues by failing a health check.

**Comment by cschneider** [comment]
I implemented the per publish agent check.

**Comment by cschneider** [comment]
@joerghoh I have discussed a way to use a feature toggle in sling with Bogdan. Possibly I will have a solution for this.

**Review by tmaret — CHANGES_REQUESTED** [review]
I wonder if it works as is. It seems the pkg offset is never set. I wonder why we need a navigable map. A navigable map would require a cleanup. I think a long (or atomic long) per sub agent could do.

**Comment by tmaret** [comment]
Just figured out the field is already set in the unchanged code (not in the diff). Also, we do require to keep track of the offsets anyway.

LGTM

**Pull request merged**
