### PR TITLE
SLING-8620 - Journal Distribution discovery service should log topolo…

### PR DESCRIPTION
**Pull request by tmaret**
…gy changes at INFO level

### CODE REVIEW

**Comment by cschneider** [comment]
The build fails as the release is not yet public. How about using the current snapshot until then?

**Comment by tmaret** [comment]
> We should take the chance and replace the String.format.

Sure, good point. Done in next commit.

**Comment by tmaret** [comment]
Regarding the snapshot, I'd prefer if we wait for the release. We should update the dependencies when it's required and not for process reason.

**Comment by tmaret** [comment]
Moved to https://github.com/apache/sling-org-apache-sling-distribution-journal/pull/11

**Pull request closed without merging**
