### PR TITLE
SLING-8944 - Systemready check for idle subscriber

### PR DESCRIPTION
**Pull request by cschneider**

### CODE REVIEW

**Comment by cschneider** [comment]
Makes sense. I have change the logic to use and busy() and idle() method. Those are simply called when package processing starts and ends. I hope this does it.

**Comment by tmaret** [comment]
The new hooks make sense to me. However, I think that there's a bug in the code. I may be mistaken since I looked at it quickly. The schedule is currently canceled with 
```
schedule.cancel(false);
```
which allows it to complete when started.

If we keep scheduling task per import, we should cancel it with

```
schedule.cancel(true);
```

**Comment by cschneider** [comment]
I think true or false only makes a difference if the task is currently running. As executing the task takes virtually no time I think it does not make sense to try to interrupt it.

**Comment by tmaret** [comment]
I think you are correct.

**Comment by tmaret** [comment]
One suggestion, when the service is ready, it is no longer necessary to schedule tasks for each import.

**Comment by cschneider** [comment]
Makes sense to not schedule when ready.

**Pull request merged**
