### PR TITLE
SLING-12218 - Remove hard queue size limit. Introduce adaptive thrott…

### PR DESCRIPTION
**Pull request by cschneider**
…ling

### CODE REVIEW

**Review by tmaret — CHANGES_REQUESTED** [review]
It makes sense to throttle. However, the proposed `getSleepTime` function looks flawed. Indeed, with the default configuration, a queue of 1 item would yield a delay of 66ms which is way more than the time required to import the item. As a result, a given producer thread will only be able to produce a couple items in the queue and the end to end latency will be impacted dramatically.

**Comment by tmaret** [comment]
I suggest to rework the `getSleepTime` as follow:

1. Introduce a delay only when the queue size is > queueSizeLimit  (0 delay otherwise)  
2. Set the delay increment as the average (measured) import latency (should be something around 2ms)
3. Delay by (queueSize - queueSizeLimit) x delayIncrement / queueSizeLimit
4. Make sure that the delay computation is not flawed by Java int arithmetic (may need to leverage float / double)

**Comment by cschneider** [comment]
How about starting delay at queueSizeLimit and reaching max delay at queueSizeLimit *2.
So we could stay with the linear approach I have but simply start delaying later.
I think the java arithmetic should be fine as the max delay is in milliseconds 20000 by default.
I don't think the delay increment has to correspond to the import latency if we start delaying later as you propose.

**Comment by cschneider** [comment]
I have now implemented the new scheme of only starting to delay at queueSizeLimit. This should make sure we operate with full performance below that limit. Above the limit delays should not have any effect on throughput as a growing queue always signals that maximum throughput on publish side is reached.

**Comment by tmaret** [comment]
Thank you, that is much better.

bq. I think the java arithmetic should be fine as the max delay is in milliseconds 20000 by default.

I would agree with you if the delay was not configurable. What happens if max delay is configured with a small number ?

bq. I don't think the delay increment has to correspond to the import latency if we start delaying later as you propose.

I think it should and be independent of the max queue size configuration. Best is to evaluate the dynamics with different configurations.

**Comment by cschneider** [comment]
I think a max delay that is much smaller than 20.000 ms would not have much effect. So in practice I think it should not be a problem.
In worst case there might be some strange jumps in delay per increase in queueSize but for maxQueueSize we know the delay would be 0 and for maxQueueSize*2 we know the delay would be maxDelay. The steps in between do not matter that much as long as they are inside the range of [0,maxDelay], which they should be.

**Comment by tmaret** [comment]
Assuming that customers will know what configuration value won't trigger rounding issues and/or select configurations that you assume are good values, seems a bit brittle and against the principle of validating user inputs. I suggest to pick any of those options to move forward : 

(a) remove the configuration after validating the values ; or 

(b) support the configuration range ; or

(c) limit the configuration range to what is effectively supported.

**Comment by cschneider** [comment]
I do not intend to offer the configuration to customers. I just use a configuration so we have a way to configure the maxQueueSize and maxDelay without doing a release.

**Comment by cschneider** [comment]
Of course this introduces the question if we should use a feature toggle.

**Comment by tmaret** [comment]
I think we should use a feature toggle and that we should go with (a) if there's no need for a customer configuration.

**Review by tmaret — APPROVED** [review]

**Pull request merged**
