### PR TITLE
SLING-10095 - Surface latest content package extractor error in the e…

### PR DESCRIPTION
**Pull request by tmaret**
…xception

### CODE REVIEW

**Comment by tmaret** [comment]
Sonar cloud marked the release instable, apparently because it failed to run the Java version installed

```
+ mvn -U clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=apache -Dsonar.projectKey=apache_sling-org-apache-sling-distribution-journal -Pjacoco-report -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-merged/jacoco.xml -Dsonar.pullrequest.branch=SLING-10095 -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=89 -Pci

----- withMaven Wrapper script -----

/home/jenkins/tools/maven/latest3/bin/mvn: 194: exec: /home/jenkins/tools/java/latest11/bin/java: Exec format error
```

https://ci-builds.apache.org/blue/organizations/jenkins/Sling%2Fmodules%2Fsling-org-apache-sling-distribution-journal/detail/PR-89/2/pipeline/33

**Comment by tmaret** [comment]
https://issues.apache.org/jira/browse/INFRA-22627

**Comment by cschneider** [comment]
Apart from the inlining I think it is good. I can understand that having the installPackage method before was not necessary but now that we do a lot more I think we should not inline.

**Comment by tmaret** [comment]
Thanks @cschneider. Inlining is not a matter of taste here. The purpose is to reduce useless entries in the logs such that deployments that cap the size of exported logs don't end up missing the relevant part.

**Comment by tmaret** [comment]
Moved the relevant part of the exception in https://github.com/apache/sling-org-apache-sling-distribution-journal/pull/90

**Pull request closed without merging**
